"""empty message

Revision ID: b16f3ff55da4
Revises: c133a6d82846
Create Date: 2024-04-21 18:15:26.641218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16f3ff55da4'
down_revision = 'c133a6d82846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
